INSERT INTO infoscreen_screen_alarmstufen VALUES ('B1', now());
INSERT INTO infoscreen_screen_alarmstufen VALUES ('B2',now());
INSERT INTO infoscreen_screen_alarmstufen VALUES ('B3',now());
INSERT INTO infoscreen_screen_alarmstufen VALUES ('B4',now());
INSERT INTO infoscreen_screen_alarmstufen VALUES ('S1',now());
INSERT INTO infoscreen_screen_alarmstufen VALUES ('S2',now());
INSERT INTO infoscreen_screen_alarmstufen VALUES ('S3',now());
INSERT INTO infoscreen_screen_alarmstufen VALUES ('T1',now());
INSERT INTO infoscreen_screen_alarmstufen VALUES ('T2',now());
INSERT INTO infoscreen_screen_alarmstufen VALUES ('T3',now());
INSERT INTO infoscreen_screen_alarmstufen VALUES ('E0',now());
