INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Autobahn - Fahrzeugbrand', 'B1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Bahndammbrand', 'B1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Brandverdacht', 'B1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Flurbrand', 'B1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Kaminbrand', 'B1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Kleinbrand', 'B1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Müllbehälterbrand', 'B1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('TUS- od. Infranet-Alarm', 'B1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Überhitzer Ofen', 'B1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Fahrzeugbrand', 'B2');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Kellerbrand', 'B2');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Küchenbrand', 'B2');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Trafobrand', 'B2');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Waldbrand', 'B2');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Wohnungsbrand', 'B2');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Zimmerbrand', 'B2');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Brand in kl. Gewerbebetrieb', 'B3');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Dachstuhlbrand', 'B3');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Geschäftsbrand', 'B3');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Gewerbebetrieb - klein', 'B3');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Scheunen- od. Schuppenbrand', 'B3');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Wohnhausbrand', 'B3');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Gewerbebetrieb - groß', 'B4');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Industrieobjekt', 'B4');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Landw. Objekt', 'B4');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Autobahn - Ölspur', 'S1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Benzin- bzw. Ölaustritt', 'S1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Benzin- bzw. Ölspur beseitigen', 'S1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Gasaustritt bzw. -gebrechen', 'S1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Autobahn - Schadstoffeinsatz', 'S2');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Chlorgasaustritt', 'S2');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Kl. Gewässerschaden', 'S2');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Öltreiben', 'S2');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Örtl. Chemieunfall', 'S2');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Chemieunfall m. größeren Umweltschäden', 'S3');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Tankwagenunfall', 'S3');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Auspumparbeiten', 'T1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Autobahn - Bergung', 'T1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Bootsbergung', 'T1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Eisstoß', 'T1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Fahrzeugbergung', 'T1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Hochwasser', 'T1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('LKW-Bergung', 'T1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Motorradbergung', 'T1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Person(en) im Aufzug', 'T1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Personensuche', 'T1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Sturmschaden', 'T1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Taucheinsatz', 'T1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Technische Hilfeleistung', 'T1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Tierrettung', 'T1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Türöffnung', 'T1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Unwettereinsatz', 'T1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Verkehrsunfall', 'T1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Wassergebrechen', 'T1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Wasserversorgung', 'T1');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Autobahn - Menschenrettung', 'T2');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Menschenrettung (1 eingekl. Person)', 'T2');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Person in Notlage', 'T2');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('VU mit 1 eingekl. Person', 'T2');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Autobahn - Schwere Bergung', 'T3');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Autobusunfall', 'T3');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Eisenbahnunglück', 'T3');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Menschenrettung (mehrere eingekl. Personen)', 'T3');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('Schiffsunglück', 'T3');
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id) VALUES ('VU mit mehreren eingekl. Personen', 'T3');
