INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Autobahn - Fahrzeugbrand', 'B1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Bahndammbrand', 'B1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Brandverdacht', 'B1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Flurbrand', 'B1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Kaminbrand', 'B1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Kleinbrand', 'B1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Müllbehälterbrand', 'B1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('TUS- od. Infranet-Alarm', 'B1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Überhitzer Ofen', 'B1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Fahrzeugbrand', 'B2',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Kellerbrand', 'B2',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Küchenbrand', 'B2',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Trafobrand', 'B2',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Waldbrand', 'B2',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Wohnungsbrand', 'B2',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Zimmerbrand', 'B2',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Brand in kl. Gewerbebetrieb', 'B3',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Dachstuhlbrand', 'B3',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Geschäftsbrand', 'B3',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Gewerbebetrieb - klein', 'B3',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Scheunen- od. Schuppenbrand', 'B3',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Wohnhausbrand', 'B3',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Gewerbebetrieb - groß', 'B4',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Industrieobjekt', 'B4',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Landw. Objekt', 'B4',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Autobahn - Ölspur', 'S1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Benzin- bzw. Ölaustritt', 'S1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Benzin- bzw. Ölspur beseitigen', 'S1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Gasaustritt bzw. -gebrechen', 'S1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Autobahn - Schadstoffeinsatz', 'S2',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Chlorgasaustritt', 'S2',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Kl. Gewässerschaden', 'S2',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Öltreiben', 'S2',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Örtl. Chemieunfall', 'S2',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Chemieunfall m. größeren Umweltschäden', 'S3',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Tankwagenunfall', 'S3',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Auspumparbeiten', 'T1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Autobahn - Bergung', 'T1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Bootsbergung', 'T1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Eisstoß', 'T1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Fahrzeugbergung', 'T1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Hochwasser', 'T1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('LKW-Bergung', 'T1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Motorradbergung', 'T1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Person(en) im Aufzug', 'T1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Personensuche', 'T1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Sturmschaden', 'T1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Taucheinsatz', 'T1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Technische Hilfeleistung', 'T1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Tierrettung', 'T1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Türöffnung', 'T1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Unwettereinsatz', 'T1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Verkehrsunfall', 'T1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Wassergebrechen', 'T1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Wasserversorgung', 'T1',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Autobahn - Menschenrettung', 'T2',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Menschenrettung (1 eingekl. Person)', 'T2',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Person in Notlage', 'T2',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('VU mit 1 eingekl. Person', 'T2',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Autobahn - Schwere Bergung', 'T3',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Autobusunfall', 'T3',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Eisenbahnunglück', 'T3',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Menschenrettung (mehrere eingekl. Personen)', 'T3',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Schiffsunglück', 'T3',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('VU mit mehreren eingekl. Personen', 'T3',datetime('now'));
INSERT INTO infoscreen_screen_meldebilder (beschreibung, stufe_id, modifiziert) VALUES ('Kein Meldebild vorhanden', 'E0',datetime('now'));
