dist/infoscreen_apache.conf /etc/infoscreen/apache

infoscreen/inc /usr/share/infoscreen/infoscreen
infoscreen/infoscreen_screen /usr/share/infoscreen/infoscreen
infoscreen/static /usr/share/infoscreen/infoscreen
infoscreen/tests /usr/share/infoscreen/infoscreen
infoscreen/tpl /usr/share/infoscreen/infoscreen
infoscreen/wsgi /usr/share/infoscreen/infoscreen
infoscreen/initial_data.json /usr/share/infoscreen/infoscreen
